### ISSUE TITLE
Can't Loot some bodies

### ISSUE THREAD

**Issue by 612aidan** [cyanobacterium/DrCyanos_Lootable-Bodies#29]
Sometimes when I die the bodies become unclickable. I can push the body around but can not punch or open the inventory. Sometimes it works like normal, but it normally
 has this issue. Reloging into the world fixes the issue but I plan to use this on a server and I can't just stop the server every time someone dies. Sometimes I can push and punch at the body (punches go right through to the block under the body) and it will let me open the inventory and punch it. I am on 1.7.10, The latest release.

![Screenshot (772)](https://user-images.githubusercontent.com/50504958/59521758-0ebf3d80-8e9b-11e9-8f69-bdca0910f177.png)
![Screenshot (773)](https://user-images.githubusercontent.com/50504958/59521777-18e13c00-8e9b-11e9-9fe5-0d4f4795f4fa.png)
![Screenshot (774)](https://user-images.githubusercontent.com/50504958/59521779-1b439600-8e9b-11e9-988d-5973a141f9c2.png)
![Screenshot (775)](https://user-images.githubusercontent.com/50504958/59521783-1d0d5980-8e9b-11e9-8afd-9129dc9a42cc.png)

**Comment by jriwanek** [comment]
No *actual* stated version, no logs demonstrating version or showing other installed provided, wrong issue tracker used.

If you wish to provide the missing information rather than just "I'm using the latest for x mc version!" then we'll be glad to assist you over on the *right* tracker at: https://github.com/MinecraftModDevelopmentMods/LootableBodies/issues
