### ISSUE TITLE
Backpacks vanish on death (not saved by body entity or dropped on ground)

### ISSUE THREAD

**Issue by julliande** [cyanobacterium/DrCyanos_Lootable-Bodies#8]
Mod Versions:
Lootable Bodies 1.3.5
Adventure Backpack 0.8b

Minecraft 1.7.10
Forge 1408

This has been tested a few times in a larger mod pack but I am pretty sure that something is not working properly between this mod and Darkona's Adventure Backpacks mod found here: 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2252109-wip-adventure-backpack-mod-beta-0-8-updated

When a player dies a body entity is spawned holding all items carried by the player including equipped items (equipped vanilla armor and baubles/tinkers construct equipables which have their own gui and inventory slots) but the backpack is nowhere to be found.

If you need more information just let me know and I'll be glad to get it for you. Also, I have reported this issue to Darkona through their issue tracker in case this is an issue on their end.

**Comment by cyanobacterium** [comment]
Are there any messages (errors or debug messages) in the log file that occur when the backpack disappears? And are the items inside the backpack on the lootable body or did they disappear with the backpack?

**Comment by julliande** [comment]
Yes all the items vanish with the backpack. Nothing stored in the backpack is stored in the body after death. When I was testing no errors showed in the console but I will run some more tests and see if I can get something in the server logs. Any ideas of what I would be looking for?

**Comment by cyanobacterium** [comment]
Look out for exceptions, because an exception on the server-side could cause Minecraft to abort the process of adding an item to the lootable body without crashing the game.

They way that the backpack and lootable bodies should work together is that when you drop your backpack upon death, the lootable body will suck it up off the ground (the process is very fast, so you usually don't see the item before it gets vacuumed up). Of course, if the backpack is not an item entity while it is on the ground, then lootable bodies cannot pick it up and it will de-spawn eventually.

**Comment by Elsys656** [comment]
I've noticed a separate issue in my case the backpack drops several blocks away usually in a vertical direction either up or down from when I died instead of being stored on my body like you might expect. It's in the same vein however.
